#baseurl:          
title:            'Digitale Geographien'
tagline:          'Forschung zu Geodaten, Code & Gesellschaft'
description:      'Ein deutschsprachiges Forschungsnetzwerk zu Geodaten, Code und Gesellschaft'
email:            kontakt@digitale-geographien.de
include:          ['_pages']
permalink:        /:categories/:slug
